### ISSUE TITLE
Reverse conversion when units provided in message?

### ISSUE THREAD

**Issue by rei-vilo** [bartbutenaers/node-red-contrib-unit-converter#1]
I'm trying to convert inches into cm. Normally, `1 in = 2.54 cm`, but I'm obtaining the reverse, `0.39`. I'm using the units as described at https://www.npmjs.com/package/convert-units#length

> {
> 	"_msgid": "474e7b43.5e6804",
> 	"topic": "",
> 	"payload": 1,
> 	"input": "in",
> 	"output": "cm",
> 	"inValue": 1,
> 	"outValue": 0.3937008
> }
> 

Shifting the `input` and `output` fields in the message gives the same result, `0.39`, which is right on that case.

Please find the whole flow. What am I doing wrong?

```
[{"id":"1cbbc4fa.2cc6bb","type":"unit-converter","z":"513420b9.c40f6","category":"apparentPower","inputUnit":"cm","outputUnit":"in","inputField":"inValue","outputField":"outValue","inputFieldType":"msg","outputFieldType":"msg","name":"","x":520,"y":480,"wires":[["dcd2cb4a.758188"]]},{"id":"6540197f.65a0f8","type":"inject","z":"513420b9.c40f6","name":"","topic":"","payload":"1","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":"","x":130,"y":420,"wires":[["66253fc0.093da"]]},{"id":"dcd2cb4a.758188","type":"debug","z":"513420b9.c40f6","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":692.9999160766602,"y":419.6666488647461,"wires":[]},{"id":"66253fc0.093da","type":"change","z":"513420b9.c40f6","name":"","rules":[{"t":"set","p":"input","pt":"msg","to":"in","tot":"str"},{"t":"set","p":"output","pt":"msg","to":"cm","tot":"str"},{"t":"set","p":"inValue","pt":"msg","to":"payload","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":329.99999618530273,"y":420.00003147125244,"wires":[["1cbbc4fa.2cc6bb","af204b75.e651d8"]]},{"id":"af204b75.e651d8","type":"debug","z":"513420b9.c40f6","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":690,"y":360,"wires":[]}]
```

However, defining the units in the **Unit converter** nodes works as expected.

Thank you!

**Comment by bartbutenaers** [comment]
Hi @rei-vilo,
Thanks for the nice description of your issue!

It seems that my readme page isn't really well explained.  This is how it works:
Let's have a look at my example flow:

![Unit conversion](https://raw.githubusercontent.com/bartbutenaers/node-red-contrib-unit-converter/master/images/unit_conversion.png)

+ The numeric input value needs to be supplied via ```msg.input```.  In your case value ```1```.
+ Then there will be a unit conversion from ```inch``` to ```cm```, as specified in the config screen.  **I have never added the possibility to specify these units in the input message!**
+ The converted numeric output value will be available in ```msg.output```

What happens in your case is that also both units are supplied via the input message (but the node will not use them!):
![image](https://user-images.githubusercontent.com/14224149/61248537-8b239580-a753-11e9-9d9d-b4d88d5f8113.png)

However in the conversion I use the units from the config screen (i.e. from ```node```): 
```
var outputValue = convert(convertedInput).from(node.inputUnit).to(node.outputUnit)
```
And the node still contains the opposite units (compared to your msg):
![image](https://user-images.githubusercontent.com/14224149/61248742-fe2d0c00-a753-11e9-91d5-7a8ef0a98c93.png)

So it converts from centimeter to inches ...

Hopefully it is a bit more clear now?
Bart

**Comment by rei-vilo** [comment]
Hi @bartbutenaers!

Thank you for the prompt and detailed answer. It is clear now.

Actually, I was misled by the `unit` term in the `Input unit` and `Output unit` descriptions provided in the Node help pane (right part of the Node-RED IDE).

> Input unit:
> The source unit of the msg.input message value.
> 
> Output unit:
> The destination unit of the msg.output message value, i.e. the value to which the value will be converted.
> 
> Input field:
> The field name in the input message, that will contain the value that needs to be converted. By default the input value will be located inside the msg.payload field.
> 
> Output field:
> The field name in the output message, that will contain the converted value. By default the output value will be located inside the msg.payload field.

However, supporting units provided in message would be a great addition to the **Unit converter** node!
