### ISSUE TITLE
Add status

### ISSUE THREAD

**Issue by schasj** [bartbutenaers/node-red-contrib-unit-converter#4]
@bartbutenaers, I'm finding this to be a very handy node and I have this feature request...How about showing the converted (output) value and units below the node, like with node.status in Function nodes?

**Comment by bartbutenaers** [comment]
Hi @schasj,
I can understand that it is useful in some use cases, but I have some doubts:
1. What if the input messagew arrive at high speed.  Then a huge amount od status data will be pushed to the flow editor.
2. You ask to show the converted value, but some other folks may want to see both the original data and the converted data.

So not sure how we should proceed with this?
Bart

**Comment by schasj** [comment]
Hi Bart,

As always, you make good points. I think both of them can be addressed by the addition of 2 check-boxes in the node's edit dialog to enable the display of in and out values. If neither is checked then it behaves as it does now.

**Comment by bartbutenaers** [comment]
@schasj,

I have implemented this feature on Github, but it is not on npm yet.
You can install it directly from Github if you want to test it.
Make sure you have git installed, and then run this command (within your .node-red folder):
```
npm install bartbutenaers/node-red-contrib-unit-converter
```
I have not updated the info panel and readme page yet.

You can choose between following types:

![image](https://user-images.githubusercontent.com/14224149/188488348-3af355ee-c01a-4742-aacd-37868d7e09f9.png)

By default you get "none" and older existing nodes will be migrated automatically to use "none" also.

The following example flow shows the visual result for every type:

![image](https://user-images.githubusercontent.com/14224149/188488551-2ede5b7e-57df-47c7-a94e-f0c65a504a08.png)
```
[{"id":"d95bdc08c72cef09","type":"unit-converter","z":"75cda3cc58138825","category":"length","inputUnit":"mm","outputUnit":"cm","inputField":"payload","outputField":"payload","inputFieldType":"msg","outputFieldType":"msg","roundOutputField":false,"outputFieldDecimals":2,"statusType":"none","name":"None","x":410,"y":380,"wires":[[]]},{"id":"af845f61e7a6743c","type":"unit-converter","z":"75cda3cc58138825","category":"length","inputUnit":"mm","outputUnit":"mm","inputField":"payload","outputField":"payload","inputFieldType":"msg","outputFieldType":"msg","roundOutputField":false,"outputFieldDecimals":2,"statusType":"units","name":"Units","x":410,"y":440,"wires":[[]]},{"id":"bf09ba9b03d32dc1","type":"unit-converter","z":"75cda3cc58138825","category":"length","inputUnit":"mm","outputUnit":"mm","inputField":"payload","outputField":"payload","inputFieldType":"msg","outputFieldType":"msg","roundOutputField":false,"outputFieldDecimals":2,"statusType":"input","name":"Input value","x":430,"y":500,"wires":[[]]},{"id":"7208e593db71dada","type":"unit-converter","z":"75cda3cc58138825","category":"length","inputUnit":"mm","outputUnit":"mm","inputField":"payload","outputField":"payload","inputFieldType":"msg","outputFieldType":"msg","roundOutputField":false,"outputFieldDecimals":2,"statusType":"output","name":"Output value","x":430,"y":560,"wires":[[]]},{"id":"560eb9595ec7365a","type":"inject","z":"75cda3cc58138825","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"100","payloadType":"num","x":230,"y":380,"wires":[["d95bdc08c72cef09","af845f61e7a6743c","bf09ba9b03d32dc1","7208e593db71dada","7fdb3dcde4f46b66"]]},{"id":"7fdb3dcde4f46b66","type":"unit-converter","z":"75cda3cc58138825","category":"length","inputUnit":"mm","outputUnit":"mm","inputField":"payload","outputField":"payload","inputFieldType":"msg","outputFieldType":"msg","roundOutputField":false,"outputFieldDecimals":2,"statusType":"inout","name":"Both values","x":430,"y":620,"wires":[[]]}]
```

Please let me know if this covers your need...

**Comment by schasj** [comment]
Bart, thanks! The only issue I see is when set it to 1 decimal place it is showing no decimal places. 

EDIT: Spoke too soon as I now see 1 decimal place. Previously, though, I saw "67F" when another instance with the same input and set to 2 decimal places showed "67.03F".

Steve (LosinIt)

**Comment by bartbutenaers** [comment]
Hey Steve,
Don't see anything weird myself about the decimal places.
Dean you mean it is ok now for you, so we can publish it on npm?

**Comment by schasj** [comment]
I don't have an example of the decimal issue ATM but I'll post here when I do and you can decide if it (or my thinking :roll_eyes: ) needs fixing. So, yes, I'm good with you publishing to npm. :+1: 

Thanks much!

**Comment by schasj** [comment]
Well that didn't take long...
Shouldn't I see 72.0 on the upper one (set to 1 decimal place) here?

![image](https://user-images.githubusercontent.com/2879461/188512038-5daba31f-54a8-4208-bb39-70251d239614.png)

Granted, it's a nit but IIRC every(?) other use of fixed decimal places pads with 0's to the specified number of places.

**Comment by bartbutenaers** [comment]
Could you please share a little example flow with an inject node, and some explanation which value you see and which you expect.   My (free) time is finished for today...

**Comment by schasj** [comment]
Certainly. What I expect to see here is that the node set to 1 decimal place (upper) displays 77.0F. The node set to 2 decimal places is as I expect.

![image](https://user-images.githubusercontent.com/2879461/188514092-62601f52-10ea-4487-a960-a1fcf09ad26e.png)

If I lower the injected value just a bit then neither is as I expect which is that the node set to 1 decimal place should be 77.0F and the node set to 2 decimal places should be 77.00F

![image](https://user-images.githubusercontent.com/2879461/188514311-e5bdd2ff-132a-4545-a75c-90fad6ddb734.png)

But this is not at all important. I only point it out because in my experience/recollection most implementations pad with zeroes to the specified number of decimal places. If you feel that it's fine the way it is then I'm good with that too.

`[{"id":"57a604308df214cf","type":"unit-converter","z":"c7ef66ad.b7fcf8","category":"temperature","inputUnit":"C","outputUnit":"F","inputField":"payload","outputField":"payload","inputFieldType":"msg","outputFieldType":"msg","roundOutputField":true,"outputFieldDecimals":"1","statusType":"output","name":"Celsius to Fahrenheit","x":650,"y":1130,"wires":[[]]},{"id":"aef75a5915b00f6c","type":"unit-converter","z":"c7ef66ad.b7fcf8","category":"temperature","inputUnit":"C","outputUnit":"F","inputField":"payload","outputField":"payload","inputFieldType":"msg","outputFieldType":"msg","roundOutputField":true,"outputFieldDecimals":"2","statusType":"output","name":"Celsius to Fahrenheit","x":650,"y":1180,"wires":[[]]},{"id":"52985d16c994a1a5","type":"inject","z":"c7ef66ad.b7fcf8","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"25.01","payloadType":"num","x":420,"y":1150,"wires":[["57a604308df214cf","aef75a5915b00f6c"]]}]`

**Comment by schasj** [comment]
The more I think about it the more I'm inclined to leave it as is. It's not worth the potential downsides.

**Comment by bartbutenaers** [comment]
Hi Steve,
Thanks for taking the time to clarify what you mean.
In fact you are right that it "might" have been more correct.
But as you also point out, it might have potential downsizes.  Since I don't know what people want to do with my node, and I always try to avoid as much as possible to break existing flows.
Therefore I am going to publish it on npm without changing this current behaviour.

**Comment by bartbutenaers** [comment]
Version ***v0.0.3*** is now available in the palette:

![image](https://user-images.githubusercontent.com/14224149/188722546-1d7c5839-4839-4ab3-bf74-be560a11f15e.png)

Enjoy it ;-)

**Comment by schasj** [comment]
Very good, Bart
